version: "3"
services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    volumes:
      - mongodb-db:/data/db
      - mongodb-configdb:/data/configdb
  notepad:
    depends_on:
    - mongodb
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: "mongodb://mongodb:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=notepad"

volumes:
  mongodb-db:
    external: true
  mongodb-configdb:
    external: true