version: "3"
services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres-db:/var/lib/postgres/data
    environment:
      - POSTGRES_PASSWORD=123456
  notepad:
    depends_on:
    - postgres
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      POSTGRES_URI: "postgres://postgres:123456@postgres:5432"
      POSTGRES_HOST: postgres
      ALLOW_USER_REGISTER: true
      SESSION_SECRET: Y0zMbk04WQX1dtpX8jJbYFA5+P6OBfUVXQjJZbde/uY=

volumes:
  postgres-db:
    external: true
